	var testData=[
		{
			id:'0'
			,name:'Kyle'
			,teir:1
			,optimize:'queen'
			,frequency:{queen:.9}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'1'
			,name:'Ryan M'
			,teir:1
			,optimize:'queen'
			,frequency:{queen:.4}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'2'
			,name:'Ryan L'
			,teir:1
			,optimize:'queen'
			,frequency:{queen:1}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'3'
			,name:'Jorge'
			,teir:1
			,optimize:'queen'
			,frequency:{queen:.5}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'4'
			,name:'Jason'
			,teir:1
			,optimize:''
			,frequency:{queen:.4}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'5'
			,name:'Jordan'
			,teir:1
			,optimize:''
			,frequency:{queen:.2}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'6'
			,name:'Eli'
			,teir:1
			,optimize:'drone'
			,frequency:{queen:0}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'7'
			,name:'Jacky'
			,teir:1
			,optimize:'drone'
			,frequency:{queen:0}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'8'
			,name:'Travis'
			,teir:1
			,optimize:'drone'
			,frequency:{queen:0}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'9'
			,name:'Bobby'
			,teir:1
			,optimize:''
			,frequency:{queen:.3}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'10'
			,name:'Forest'
			,teir:1
			,optimize:''
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'11'
			,name:'P'
			,teir:1
			,optimize:''
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'12'
			,name:'Tyler'
			,teir:1
			,optimize:''
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'13'
			,name:'John'
			,teir:1
			,optimize:'queen'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'14'
			,name:'Steven'
			,teir:1
			,optimize:'drone'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'15'
			,name:'Aaron'
			,teir:1
			,optimize:'drone'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'16'
			,name:'Andrew'
			,teir:1
			,optimize:'queen'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'17'
			,name:'Emily'
			,teir:1
			,optimize:'drone'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'18'
			,name:'Will'
			,teir:1
			,optimize:'drone'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'19'
			,name:'NoobQueen'
			,teir:1
			,optimize:'queen'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'20'
			,name:'NoobDrone'
			,teir:1
			,optimize:'drone'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'21'
			,name:'NoobPlay'
			,teir:1
			,optimize:''
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'22'
			,name:'QueenOnly'
			,teir:1
			,optimize:'queenOnly'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		},{
			id:'23'
			,name:'DroneOnly'
			,teir:1
			,optimize:'droneOnly'
			,frequency:{queen:.8}
			,stats:{
				queen:{military:[0,0],snail:[0,0],berries:[0,0]}
				,drone:{military:[0,0],snail:[0,0],berries:[0,0]}
			}
			,history:{
				games:0
				,asQueen:0
				,asDrone:0
			}
		}



	];
